apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-demo
  template:
    metadata:
      labels:
        app: spring-demo
    spec:
      containers:
        - name: spring-demo
          image: 281934899210.dkr.ecr.us-east-1.amazonaws.com/spring-demo:latest
          ports:
            - containerPort: 8080