version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    ECR_REPO: spring-demo
    CLUSTER_NAME: my-eks-cluster

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing kubectl
      - curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.0/2024-01-04/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo Logging in to ECR
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Build Spring Boot
      - mvn clean package
      - docker build -t $ECR_REPO .
      - docker tag $ECR_REPO:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest

  post_build:
    commands:
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
      - echo Updating kubeconfig
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
      - kubectl apply -f k8s/deployment.yaml
      - kubectl apply -f k8s/service.yaml

artifacts:
  files:
    - '**/*'